/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentRouteImport } from './routes/content'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiPublicLeaderboardRouteImport } from './routes/api/public/leaderboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeaderboardRoute = ApiPublicLeaderboardRouteImport.update({
  id: '/api/public/leaderboard',
  path: '/api/public/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/content': typeof ContentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/leaderboard': typeof ApiPublicLeaderboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/content': typeof ContentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/leaderboard': typeof ApiPublicLeaderboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/content': typeof ContentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/leaderboard': typeof ApiPublicLeaderboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/content' | '/sitemap.xml' | '/api/public/leaderboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/content' | '/sitemap.xml' | '/api/public/leaderboard'
  id: '__root__' | '/' | '/content' | '/sitemap.xml' | '/api/public/leaderboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentRoute: typeof ContentRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicLeaderboardRoute: typeof ApiPublicLeaderboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leaderboard': {
      id: '/api/public/leaderboard'
      path: '/api/public/leaderboard'
      fullPath: '/api/public/leaderboard'
      preLoaderRoute: typeof ApiPublicLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentRoute: ContentRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicLeaderboardRoute: ApiPublicLeaderboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
